name: resolve
on:
  pull_request:
    paths:
      - "packages/**"
      - "model.json"
jobs:
  resolve:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: "lts/*" }
      - run: npm install
      - run: node packages/resolve/resolve.mjs model.json
